apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-jdbc
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: spring-jdbc
  template:
    metadata:
      labels:
        app: spring-jdbc
    spec:
      containers:
# to fetch image from dockerhub, uncomment following line
#        - image: shitalm/spring-jdbc:1.0
# to fetch image from dockerhub, comment out two subsequent lines
        - image: spring-jdbc:local
          imagePullPolicy: Never
          name: spring-jdbc
          ports:
            - containerPort: 80
          env:
          - name: spring_profiles_active
            value: prod